In [1]:
!nvidia-smi

Sun Dec  8 04:33:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


Pytorch tensors are creted using "torch.tensor()"

Scalar

In [3]:
#intro to tensor
#scalar tensor

scalar=torch.tensor(10)
scalar

tensor(10)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

10

Vector

In [8]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

MATRIX

In [13]:
MATRIX= torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX.shape

torch.Size([2, 2])

TENSOR

In [21]:
TENSOR=torch.tensor([[[1,2,3],
 [4,5,6],
  [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

the output of code means there is 1 dimention of 3 X 3

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

###Random Tensors

random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.


"start with random numbers-> look at data -> update random numbers-> look at data-> update random numbers"

In [29]:
#craeting random tensors of dimension 2 of  3 x 4 matrix
random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.3884, 0.3544, 0.5715, 0.8600],
        [0.6566, 0.3694, 0.8477, 0.3644],
        [0.8590, 0.5307, 0.3775, 0.5937]])

In [30]:
random_tensor.ndim

2

random tensor with same shape of image tensor

In [31]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###zeros and ones **tensor**

In [32]:
zeros= torch.zeros(size=(4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [33]:
ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype #default datatype

torch.float32

###creating a range of tensors and tensors-like

In [39]:
one_to_ten = torch.arange(1,12,2)

In [40]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

###Tensor datatypes

In [41]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [42]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

###Tensor Attributes

##getting information from tensors

1) Tensors not right datatype- to do get datatype from a tensor, can use tensor.datatype
2) tensor not right shape- to get shape use tensor.shape
3) Tensor not on the right devic- to get device from a tensor, can use tensor.device

In [43]:
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.3874, 0.6906, 0.8582, 0.5111],
        [0.0790, 0.1510, 0.1903, 0.7575],
        [0.2836, 0.4139, 0.1115, 0.8810]])

In [44]:
#details about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3874, 0.6906, 0.8582, 0.5111],
        [0.0790, 0.1510, 0.1903, 0.7575],
        [0.2836, 0.4139, 0.1115, 0.8810]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


#Manipulating tensors (Tensor operations)

* Addition
* Substraction
* Multiplication
* Division
* Matrix Multiplication

In [47]:
#Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10



tensor([11, 12, 13])

In [48]:
#substraction
tensor-10

tensor([-9, -8, -7])

In [49]:
#multiplication
tensor *10

tensor([10, 20, 30])

In [50]:
#division
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

#matrix multiplication

* Elementwise
* dot product


In [51]:
#element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [52]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [53]:
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)


In [54]:
torch.matmul(tensor,tensor)

tensor(14)

##common errors in  deep learning
shape error
1. The **inner dimensions** must match:
  * (3, 2) @ (3, 2) won't work
  * (2, 3) @ (3, 2) will work
  * (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of **outer dimension**
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)

In [58]:
torch.rand(3,2) @ torch.rand(3,2)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [59]:
torch.rand(2,3) @ torch.rand(3,2)

tensor([[0.7416, 0.8852],
        [0.4638, 0.5240]])

In [60]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.2231, 0.1406, 0.1408],
        [0.4013, 0.2829, 0.2938],
        [0.6303, 0.3778, 0.3719]])

In [63]:
tensor_A = torch.tensor([[1, 2],
                         [3,4],
                         [5,6]], dtype = torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype = torch.float32)

print(tensor_A)
print(tensor_B)

print(tensor_A.shape)
print(tensor_B.shape)



tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
torch.Size([3, 2])
torch.Size([3, 2])


In [64]:
print(torch.mm(tensor_A, tensor_B))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

#Finding min,max,sum,avg

In [65]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
x.min()

tensor(0)

In [68]:
x.max()

tensor(90)

In [69]:
x.avg()

AttributeError: 'Tensor' object has no attribute 'avg'

In [71]:
torch.mean(x.type(torch.float32))

tensor(45.)

#positional min and max

In [72]:
x.argmin()

tensor(0)

In [73]:
x.argmax()

tensor(9)

##Reshaping, stacking, squeezing,unsqueezing
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)


* Squeeze - removes all 1 dimension to a target tensor
* Unsqueeze - add 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [74]:
x= torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [75]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
#change view
z= x.view(1,9)
z,z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [81]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:
torch.squeeze(x_reshaped)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [84]:
torch.unsqueeze(x_reshaped,dim=0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [85]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [89]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

Indexing (selecting data from tensors)
Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

If you've ever done indexing on Python lists or NumPy arrays, indexing in PyTorch with tensors is very similar.

In [90]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [92]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [93]:

# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [94]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])


PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [95]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [98]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))